# Generated by Django 5.1.4 on 2026-03-15 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compra_itemcompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingrediente',
            name='estoque_atual',
        ),
        migrations.RemoveField(
            model_name='ingrediente',
            name='unidade',
        ),
        migrations.AddField(
            model_name='compra',
            name='local',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
