# Generated by Django 5.1.4 on 2026-03-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ingrediente_estoque_atual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
