# Generated by Django 5.1.4 on 2026-03-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='gramas_por_unidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='valor_pacote',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
