# Generated by Django 5.1.4 on 2026-03-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingrediente_gramas_por_unidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='estoque_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='pedido',
            name='baixa_estoque_aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
